{
 "title": "Sui monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Proposer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "num_of_batch_digests_in_header",
   "type": "timeseries",
   "description": "The number of batch digests included in a proposed header. A reason label is included.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(narwhal_primary_num_of_batch_digests_in_header_bucket{le=\"+Inf\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "header_to_certificate_latency",
   "type": "timeseries",
   "description": "Time it takes for a header to be materialised to a certificate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(narwhal_primary_header_to_certificate_latency_bucket{le=\"+Inf\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "proposer_batch_latency",
   "type": "timeseries",
   "description": "The latency of a batch between the time it has been created and until it has been included to a header proposal.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(narwhal_primary_proposer_batch_latency_bucket{le=\"+Inf\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "num_of_pending_batches_in_proposer",
   "type": "timeseries",
   "description": "Number of batch digests pending in proposer for next header proposal",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "narwhal_primary_num_of_pending_batches_in_proposer",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Consensus commit round latency",
   "type": "timeseries",
   "description": "The latency between two successful commit rounds (when we have successful leader election)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(narwhal_primary_consensus_commit_rounds_latency_bucket{le=\"+Inf\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dag round",
   "type": "timeseries",
   "description": "The number of rounds for which the consensus Dag holds certificates",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "narwhal_primary_consensus_dag_rounds{job=\"node\", instance=\"localhost:6000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current round",
   "type": "timeseries",
   "description": "current consensus round",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "narwhal_primary_current_round{job=\"node\", instance=\"localhost:6000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "subscriber_current_round",
   "type": "timeseries",
   "description": "Round of last certificate seen by subscriber",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "narwhal_primary_subscriber_current_round",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "subscriber_processed_batches",
   "type": "timeseries",
   "description": "Number of batches processed by subscriber",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "narwhal_primary_subscriber_processed_batches",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "subscriber_certificate_latency",
   "type": "timeseries",
   "description": "Latency between when the certificate has been created and when it reached the executor",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(narwhal_primary_subscriber_certificate_latency_bucket{le=\"+Inf\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "batch_execution_latency",
   "type": "timeseries",
   "description": "Latency between the time when the batch has been created and when it has been fetched for execution",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "rate(narwhal_primary_batch_execution_latency_bucket{le=\"+Inf\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "batch_execution_local_latency",
   "type": "timeseries",
   "description": "This is similar to batch_execution_latency but without the latency of fetching batches from remote workers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(narwhal_primary_batch_execution_local_latency_bucket{le=\"+Inf\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "waiting_elements_subscriber",
   "type": "timeseries",
   "description": "The number of pending payload downloads",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "narwhal_primary_waiting_elements_subscriber",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}